// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeItUpData.Library.DataAccess;

namespace TimeItUpData.Library.Migrations
{
    [DbContext(typeof(EFDbContext))]
    partial class EFDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeItUpData.Library.Models.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TimerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ActivationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TimerId1")
                        .HasColumnType("int");

                    b.Property<int>("TimerUserId")
                        .HasColumnType("int");

                    b.HasKey("Id", "TimerId");

                    b.HasIndex("TimerId1", "TimerUserId");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.Pause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TimerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimerId1")
                        .HasColumnType("int");

                    b.Property<int>("TimerUserId")
                        .HasColumnType("int");

                    b.Property<string>("TotalDuration")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeSpan>("TotalDurationTimeSpan")
                        .HasColumnType("time");

                    b.HasKey("Id", "TimerId");

                    b.HasIndex("TimerId1", "TimerUserId");

                    b.ToTable("Pauses");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.Split", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TimerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimerId1")
                        .HasColumnType("int");

                    b.Property<int>("TimerUserId")
                        .HasColumnType("int");

                    b.Property<string>("TotalDuration")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeSpan>("TotalDurationTimeSpan")
                        .HasColumnType("time");

                    b.HasKey("Id", "TimerId");

                    b.HasIndex("TimerId1", "TimerUserId");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.Timer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Paused")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TotalCountdownTime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeSpan>("TotalCountdownTimeSpan")
                        .HasColumnType("time");

                    b.Property<string>("TotalDuration")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeSpan>("TotalDurationTimeSpan")
                        .HasColumnType("time");

                    b.Property<string>("TotalPausedTime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeSpan>("TotalPausedTimeSpan")
                        .HasColumnType("time");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Timers");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.Alarm", b =>
                {
                    b.HasOne("TimeItUpData.Library.Models.Timer", "Timer")
                        .WithMany("Alarms")
                        .HasForeignKey("TimerId1", "TimerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timer");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.Pause", b =>
                {
                    b.HasOne("TimeItUpData.Library.Models.Timer", "Timer")
                        .WithMany("Pauses")
                        .HasForeignKey("TimerId1", "TimerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timer");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.Split", b =>
                {
                    b.HasOne("TimeItUpData.Library.Models.Timer", "Timer")
                        .WithMany("Splits")
                        .HasForeignKey("TimerId1", "TimerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timer");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.Timer", b =>
                {
                    b.HasOne("TimeItUpData.Library.Models.User", "User")
                        .WithMany("Timers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.Timer", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Pauses");

                    b.Navigation("Splits");
                });

            modelBuilder.Entity("TimeItUpData.Library.Models.User", b =>
                {
                    b.Navigation("Timers");
                });
#pragma warning restore 612, 618
        }
    }
}
